version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopproject-web:prod
    container_name: shop-web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "8080"
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: shop-nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
